# must accept EULA the first time that the image is started
# docker run splunk/splunk
# Options on how to review the EULA and accept it: 
# 1. docker run -it splunk/splunk
# 2. Add the following environment variable: SPLUNK_START_ARGS=--accept-license
# e.g., docker run -e "SPLUNK_START_ARGS=--accept-license" splunk/splunk 

# Support for Docker Compose, https://docs.docker.com/compose/overview/
version: '3'
services:
  splunkenterprise:
    #build: .
    hostname: splunkenterprise
    image: splunk/splunk:7.0.3-monitor
    environment:
      SPLUNK_START_ARGS: --accept-license --answer-yes
      SPLUNK_ENABLE_LISTEN: 9997
      SPLUNK_ADD: tcp 1514
#      SPLUNK_USER: root
    ports:
      - "8000:8000"
      - "9997:9997"
      - "8088:8088"
      - "1514:1514"
    volumes:
      - vsplunk-opt-splunk-etc:/opt/splunk/etc
      - vsplunk-opt-splunk-var:/opt/splunk/var 

volumes:
  vsplunk-opt-splunk-etc:
  vsplunk-opt-splunk-var: