# must accept EULA the first time that the image is started
# docker run splunk/universalforwarder:6.5.3
# Options on how to review the EULA and accept it: 
# 1. docker run -it splunk/universalforwarder:6.5.3
# 2. Add the following environment variable: SPLUNK_START_ARGS=--accept-license
# e.g., docker run -e "SPLUNK_START_ARGS=--accept-license" splunk/splunkuniversalforwarder:6.5.3 
version: '2'
services:
  vsplunk_uf:
    image: busybox
    volumes:
      - /opt/splunk/etc
      - /opt/splunk/var
  splunkuniversalforwarder:
    hostname: splunkuniversalforwarder
    image: splunk/universalforwarder:6.5.3-monitor
#    environment:
#      SPLUNK_START_ARGS: --accept-license --answer-yes
#      SPLUNK_FORWARD_SERVER: 192.168.99.100:9997
#      SPLUNK_USER: root
      # this will insure we can scale out into a swarm
      # and only schedule 1 contianer per host
#      affinity: container!=~*splunkuniversalforwarder*
    restart: always
    volumes_from:
      - vsplunk_uf
    volumes:
      - /var/lib/docker/containers:/host/containers:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro
#    ports:
#      - "8088:8088"
#      - "1514:1514" 